name: e_commerce_usama_elgendy
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  google_sign_in: ^6.1.4
  cloud_firestore: ^4.8.2
  flutter_slidable: ^3.0.0
#  new_version: ^0.3.1
#  in_app_update: ^4.1.4
  shared_preferences: ^2.2.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

